### ISSUE TITLE
Memory allocation failed

### ISSUE THREAD

**Issue by XanthusL** [BurntSushi/aho-corasick#44] opened 2019-07-10 06:04 UTC
```rs
use aho_corasick::AhoCorasickBuilder;
use std::fs::File;
use std::io::Read;

fn main() {
    let mut f = File::open("keyword.txt").unwrap();
    let mut dat = String::new();
    f.read_to_string(&mut dat).unwrap();
    let words = dat.split("\n");
    let mut v = vec![];
    for i in words {
        v.push(i);
    }
    AhoCorasickBuilder::new()
        .ascii_case_insensitive(true)
        .build(&v);
}

```
memory allocation of 1629519872 bytes failed
[1]    13458 abort (core dumped)  cargo run

```sh
free -h
              total        used        free      shared  buff/cache   available
Mem:          7.6Gi       4.0Gi       2.9Gi       492Mi       752Mi       2.9Gi
Swap:            0B          0B          0B
```
https://github.com/observerss/textfilter/blob/master/keywords

**Comment by BurntSushi** [comment] 2019-07-10 10:58
It looks like there's a bug in the handling of ASCII case insensitivity, since if you disable that, then the automaton compiles successfully.

I'm not sure what the cause of the bug is yet.

**Comment by BurntSushi** [comment] 2019-08-01 22:54
This was a nice bug. Thanks for reporting it. It _looks_ like it was an infinite loop that kept allocating memory, but it turned out to be exponential. Namely, the code that filled in the failure transitions of the automaton assumed that it would never enqueue the same state twice. But when it does, it visits everything recursively, so `abcdefg` ends up queueing something around `2^len(abcdefg) == 128` states instead of only `7` states. Some of your patterns are over 60 bytes long, so `2^60` is a big number. :-)

I have a fix for this locally which I should be pushing soon among other things.

**Closed** 2019-08-03 13:47 UTC
Labels: bug
